#!/usr/bin/env perl

use Modern::Perl;
use IO::All;
use Smart::Comments;
use IPC::Cmd qw(can_run);
use File::Basename;
use File::Spec;
use File::Path qw(mkpath);
use Readonly;
use Pod::Simple::HTMLBatch;

Readonly my $HTML_OUTPUT_DIR => File::Spec->catdir('Perlbrew.docset', 'Contents', 'Resources', 'Documents');
Readonly my $INFO_PLIST      => File::Spec->catdir('Perlbrew.docset', 'Contents', 'Info.plist');

my $perl_exe     = can_run('perl');
my $perl_bin_dir = dirname($perl_exe);
my $perl_lib_dir = File::Spec->catdir($perl_bin_dir, '..', 'lib');
my $perl_version = basename((grep { ! /site_perl/ } glob File::Spec->catfile($perl_lib_dir, '*'))[0]);

my $perl_libraries      = File::Spec->catdir($perl_lib_dir, $perl_version);
my $site_perl_libraries = File::Spec->catdir($perl_lib_dir, 'site_perl', $perl_version);

my $perl_html_dir = File::Spec->catdir($HTML_OUTPUT_DIR, $perl_version);
my $site_perl_html_dir = File::Spec->catdir($HTML_OUTPUT_DIR, 'site_perl', $perl_version);

=pod
mkpath $perl_html_dir;
mkpath $site_perl_html_dir;

my $batchconv = Pod::Simple::HTMLBatch->new;
$batchconv->batch_convert( $perl_libraries,      $perl_html_dir      );
$batchconv->batch_convert( $site_perl_libraries, $site_perl_html_dir );

my $info_plist_content = << 'END';
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleIdentifier</key>
	<string>Perl</string>
	<key>CFBundleName</key>
	<string>Perl</string>
	<key>DocSetPlatformFamily</key>
	<string>Perl</string>
	<key>isDashDocset</key>
	<true/>
</dict>
</plist>
END

$info_plist_content > io($INFO_PLIST);
=cut
